import React from 'react';

const FooterComponent = () => {
  const footerStyle = {
    padding: '20px',
    textAlign: 'center',
    fontSize: '12px',
    color: '#666',
    borderTop: '1px solid #eee',
    marginTop: '20px'
  };

  const nameStyle = {
    fontWeight: 'bold',
    color: '#007bff'
  };

  return (
    <footer style={footerStyle}>
      <p>
        Report and Content generated by <span style={nameStyle}>Shree Krishna Computers</span>.
      </p>
      <p>For Contacting mail us on  : kanhaiyay318@gmail.com</p>
      <p style={{ fontSize: '10px', marginTop: '5px' }}>
        &copy; {new Date().getFullYear()} PC Build, Parts Marketplace & Repair Solution. All rights reserved.
      </p>
    </footer>
  );
};

export default FooterComponent;